### ISSUE TITLE
Create default keystore if one doesn't exist.

### ISSUE THREAD

**Issue by ShaneMcC** [DFBnc/DFBnc#107]
If we are started with SSL and no keystore exists, we should probably create one.

At the very least, the Dockerfile should do it for Docker versions.

**Comment by ShaneMcC** [comment]
You can now use pem files which are a boat-load nicer and we'll probably deprecate the keystore in future so meh to this.

**Comment by greboid** [comment]
I think the general principal still applies though, you should probably generate a new PEM if none exists and its been started with SSL.

**Comment by greboid** [comment]
Just noticed this is still open and you closed it once.  I did add support for auto generation when running in Docker, so I'll close this off again.
