### ISSUE TITLE
Add way to reload certificates

### ISSUE THREAD

**Issue by csmith** [DFBnc/DFBnc#134]
If we're thinking about using Let's Encrypt, there needs to be a way to tell DFBnc to reload the certificates (which I think should just be a case of nulling the SSLContext held in SSLContextManager, and allowing it to be recreated next session).

From a completely external point of view, being able to send a HUP and have DFBnc reload would be the best. There's an undocumented API in sun.misc.Signal for handling signals in Java.

Alternatively, DFBnc could have a command line argument to reload and do some kind of IPC itself (but that seems a little overkill).

**Comment by ShaneMcC** [comment]
I think HUP and then re-reading the SSL certs makes sense, but I don't think it could reload the entire config in a sane way.
