### ISSUE TITLE
TLS connections can take up to a minute to negotiate

### ISSUE THREAD

**Issue by csmith** [DFBnc/DFBnc#152]
This is something both @greboid and I have noticed.

After hours of debugging I've concluded:

- This issue happens with bouncers running both in and out of docker
- The issue is reproducible with `openssl s_client`, so it's not an IRC client issue
- The client requests a cipher change and the server stops responding
- An arbitrary amount of time later the server sends a PING to all open sockets
- Sending the ping wakes the socket selector and changes the interestOps
- The TLS handshake fully completes immediately thereafter

I think that SSLEngine isn't being used right. You're calling beginHandshake and then leaving it to its own devices. [This sample code](https://github.com/alkarn/sslengine.example/blob/master/src/main/java/alkarn/github/io/sslengine/example/NioSslPeer.java#L117) does an awful lot more handholding during the handshake.

My theory is without this extra work, SSLEngine is only able to send/receive data when you happen to fiddle with the socket selector (such as when a PING is sent, or the initial NOTICE AUTH lines). I don't see a sane way to test that theory without implementing it all though!

**Comment by ShaneMcC** [comment]
So, I do already handhold a bit more than just calling `beginHandshake()` (https://github.com/DFBnc/sockets/blob/master/src/com/dfbnc/sockets/secure/SSLByteChannel.java#L290) but I'm obviously doing something wrong, will take a look.

**Comment by ShaneMcC** [comment]
Looks like I was breaking out of the handshake loop too early in some instances. (This break is in place to stop plain text sockets connecting and causing us to sit `UNWRAP`ing forever).

Fixed.

Thanks for the report, troubleshooting and sample code.
